CREATE TABLE "TB_USER" (
	"USER_ID"	VARCHAR2(100)		NOT NULL,
	"USER_PW"	VARCHAR2(256)		NOT NULL,
	"USER_NICKNAME"	VARCHAR2(32)		NOT NULL,
	"USER_NAME"	VARCHAR2(32)		NOT NULL,
	"USER_PHONE"	VARCHAR2(32)		NOT NULL,
	"USER_EMAIL"	VARCHAR2(128)		NULL,
	"FAIL_CNT"	NUMBER(2)	DEFAULT 0	NULL,
	"SALT"	VARCHAR2(32)		NOT NULL,
	"ROLE"	NUMBER(2)	DEFAULT 0	NOT NULL,
	"STATUS"	NUMBER(2)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "TB_USER"."USER_ID" IS '회원식별자';

COMMENT ON COLUMN "TB_USER"."USER_PW" IS '계정 비밀번호';

COMMENT ON COLUMN "TB_USER"."USER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "TB_USER"."USER_NAME" IS '회원명';

COMMENT ON COLUMN "TB_USER"."USER_PHONE" IS '회원 연락처';

COMMENT ON COLUMN "TB_USER"."USER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "TB_USER"."FAIL_CNT" IS '로그인 실패 카운트';

COMMENT ON COLUMN "TB_USER"."SALT" IS 'PW 암호화용 코드';

COMMENT ON COLUMN "TB_USER"."ROLE" IS '회원 권한 구분';

COMMENT ON COLUMN "TB_USER"."STATUS" IS '회원 탈퇴, 차단 구분';

CREATE TABLE "TB_BOARD" (
	"BOARD_NO"	VARCHAR(255)		NOT NULL,
	"USER_ID"	VARCHAR2(100)		NOT NULL,
	"TYPE_BOARD"	NUMBER(2)	DEFAULT 0	NOT NULL,
	"BOARD_CATEGORY"	VARCHAR2(32)		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(128)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_DATE"	VARCHAR2(32)	DEFAULT SYSDATE	NULL,
	"BOARD_HIT"	VARCHAR2(10)	DEFAULT 0	NOT NULL,
	"BOARD_STATUS"	NUMBER(2)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "TB_BOARD"."BOARD_NO" IS '글 번호';

COMMENT ON COLUMN "TB_BOARD"."USER_ID" IS '회원식별자';

COMMENT ON COLUMN "TB_BOARD"."TYPE_BOARD" IS '좋아요,신고용 타입';

COMMENT ON COLUMN "TB_BOARD"."BOARD_CATEGORY" IS '글 카테고리';

COMMENT ON COLUMN "TB_BOARD"."BOARD_TITLE" IS '글 제목';

COMMENT ON COLUMN "TB_BOARD"."BOARD_CONTENT" IS '글 내용';

COMMENT ON COLUMN "TB_BOARD"."BOARD_DATE" IS '작성일';

COMMENT ON COLUMN "TB_BOARD"."BOARD_HIT" IS '조회수';

COMMENT ON COLUMN "TB_BOARD"."BOARD_STATUS" IS '게시글 차단 구분 디폴트:0 / 차단:1';

CREATE TABLE "TB_B_COMMENT" (
	"BOARD_NO"	NUMBER(10)		NOT NULL,
	"USER_ID"	VARCHAR2(100)		NOT NULL,
	"TYPE_COMMENT"	NUMBER(2)	DEFAULT 1	NOT NULL,
	"COMMENT_NO"	NUMBER(10)		NOT NULL,
	"COMMENT_STEP"	INT	DEFAULT 0	NULL,
	"COMMENT_CONTENT"	VARCHAR2(400)		NOT NULL,
	"COMMENT_DATE"	VARCHAR2(32)	DEFAULT SYSDATE	NULL,
	"COMMENT_STATUS"	NUMBER(2)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "TB_B_COMMENT"."BOARD_NO" IS '글 번호';

COMMENT ON COLUMN "TB_B_COMMENT"."USER_ID" IS '회원식별자';

COMMENT ON COLUMN "TB_B_COMMENT"."TYPE_COMMENT" IS '좋아요,신고용 타입';

COMMENT ON COLUMN "TB_B_COMMENT"."COMMENT_NO" IS '글번호';

COMMENT ON COLUMN "TB_B_COMMENT"."COMMENT_STEP" IS '대댓글 번호댓글 : 0/대댓글 : N+1';

COMMENT ON COLUMN "TB_B_COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "TB_B_COMMENT"."COMMENT_DATE" IS '댓글 작성일
"YYYY-MM-DD HH:MM:SS"';

COMMENT ON COLUMN "TB_B_COMMENT"."COMMENT_STATUS" IS '댓글 삭제,차단 구분 디폴트:0 /삭제:1/ 차단:2';

CREATE TABLE "TB_B_FILE" (
	"FILE_NO"	NUMBER(10)		NOT NULL,
	"BOARD_NO"	NUMBER(10)		NOT NULL,
	"FILE_NAME"	VARCHAR2(500)		NOT NULL,
	"FILE_URL"	VARCHAR2(500)		NOT NULL,
	"FILE_SIZE"	NUMBER(10, 2)		NOT NULL,
	"FILE_TYPE"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "TB_B_FILE"."FILE_NO" IS '파일 번호';

COMMENT ON COLUMN "TB_B_FILE"."BOARD_NO" IS '글 번호';

COMMENT ON COLUMN "TB_B_FILE"."FILE_NAME" IS '파일 이름';

COMMENT ON COLUMN "TB_B_FILE"."FILE_URL" IS '파일 url';

COMMENT ON COLUMN "TB_B_FILE"."FILE_SIZE" IS '파일 크기';

COMMENT ON COLUMN "TB_B_FILE"."FILE_TYPE" IS '파일타입';

CREATE TABLE "TB_LIKE" (
	"LIKE_NO"	NUMBER(20)		NOT NULL,
	"USER_ID"	VARCHAR2(100)		NOT NULL,
	"LIKE_TYPE"	NUMBER(2)		NOT NULL,
	"LIKE_GROUP"	NUMBER(10)		NULL,
	"LIKE_STEP"	NUMBER(10)		NULL,
	"LIKE_DATE"	VARCHAR2(32)	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "TB_LIKE"."LIKE_NO" IS '글 번호(중복 좋아요 방지)';

COMMENT ON COLUMN "TB_LIKE"."USER_ID" IS '회원식별자';

COMMENT ON COLUMN "TB_LIKE"."LIKE_TYPE" IS '좋아요용 타입 글:0/댓글:1/';

COMMENT ON COLUMN "TB_LIKE"."LIKE_GROUP" IS '해당 글, 댓글, 리뷰의  번호';

COMMENT ON COLUMN "TB_LIKE"."LIKE_STEP" IS '대댓글 번호 댓글:0 / 대댓글:1이상 SEQ';

COMMENT ON COLUMN "TB_LIKE"."LIKE_DATE" IS '좋아요 날짜';

CREATE TABLE "TB_REPORT" (
	"REPORT_NO"	NUMBER(10)		NOT NULL,
	"USER_ID"	VARCHAR2(100)		NOT NULL,
	"REPORT_TYPE"	NUMBER(2)		NOT NULL,
	"REPORT_NUM"	NUMBER(10)		NOT NULL,
	"REPORT_GROUP"	NUMBER(10)	DEFAULT -1	NULL,
	"REPORT_STEP"	NUMBER(2)	DEFAULT 0	NULL,
	"REPORT_USER"	VARCHAR2(100)		NOT NULL,
	"REPORT_REASON"	VARCHAR2(200)		NOT NULL,
	"REPORT_DATE"	VARCHAR2(32)	DEFAULT SYSDATE	NOT NULL,
	"REPORT_RESULT"	NUMBER(2)	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "TB_REPORT"."REPORT_NO" IS '신고 번호';

COMMENT ON COLUMN "TB_REPORT"."USER_ID" IS '회원식별자';

COMMENT ON COLUMN "TB_REPORT"."REPORT_TYPE" IS '신고된 글의 종류::  글:0/댓글:1';

COMMENT ON COLUMN "TB_REPORT"."REPORT_NUM" IS '글 번호';

COMMENT ON COLUMN "TB_REPORT"."REPORT_GROUP" IS '댓글 번호';

COMMENT ON COLUMN "TB_REPORT"."REPORT_STEP" IS '대댓글 번호 댓글:0 / 대댓글:1';

COMMENT ON COLUMN "TB_REPORT"."REPORT_USER" IS '신고 대상';

COMMENT ON COLUMN "TB_REPORT"."REPORT_REASON" IS '신고 사유';

COMMENT ON COLUMN "TB_REPORT"."REPORT_DATE" IS '신고 날짜';

COMMENT ON COLUMN "TB_REPORT"."REPORT_RESULT" IS '디폴트 :0/처리완료:1';

ALTER TABLE "TB_USER" ADD CONSTRAINT "PK_TB_USER" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "TB_BOARD" ADD CONSTRAINT "PK_TB_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "TB_B_FILE" ADD CONSTRAINT "PK_TB_B_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "TB_LIKE" ADD CONSTRAINT "PK_TB_LIKE" PRIMARY KEY (
	"LIKE_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "PK_TB_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

